### ISSUE TITLE
VFIO is not strictly tied to KVM

### ISSUE THREAD

**Issue by liuw** [rust-vmm/vfio-ioctls#2]
The `new` function wants to take a KVM VFIO device.

https://github.com/rust-vmm/vfio-ioctls/blob/0f4ee9f33a7de7b3354cbed94939e4bc6f8253ec/src/vfio_device.rs#L145

This is fine within the context of rust-vmm, but userspace drivers may not care about KVM at all. Removing this restriction can potentially make this crate more useful to a wider audience.

**Comment by andreeaflorescu** [comment]
We could have an unsafe `new_raw` that takes as a parameter a `RawFd` instead of a DeviceFd. Would that work out for other use cases?

**Comment by liuw** [comment]
> 
> 
> We could have an unsafe `new_raw` that takes as a parameter a `RawFd` instead of a `DeviceFd`, or a `new_from_fd` that takes as a parameter `T: AsRawFd` (such that it is safe). Would that work out for other use cases?

Thanks for the quick reply.

My use case in mind is to make this work with MSHV as well, but that's not the reason why this issue is created. Your suggestion here is what I want to explore when we come to invent a `DeviceFd` for MSHV, but that's further down the road.

Like I said, userspace drivers don't care about virtualization, and by extension, don't really want to create a KVM or MSHV `DeviceFd` for the sake of using this crate. This is what I want to raise in this issue.

**Comment by jiangliu** [comment]
It's a little complex to move kvm_device_add_group/kvm_device_del_group out of vfio_ioctl, we may use feature to conditionally support kvm related logic.

**Comment by liuw** [comment]
> 
> 
> It's a little complex to move kvm_device_add_group/kvm_device_del_group out of vfio_ioctl, we may use feature to conditionally support kvm related logic.

There is no need to move the logic out. One option is to make the `DeviceFd` optional and only issue KVM related calls when that's provided. The other option is to use a feature gate like you suggested.

I will try to write some patches when I have some copious free time for further discussion.

**Comment by jiangliu** [comment]
closed via #44
